sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1


before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in angular-yeti-258803-f247447d7224.json.enc -out angular-yeti-258803-f247447d7224.json -d
  - gcloud auth activate-service-account --key-file angular-yeti-258803-f247447d7224.json
  - gcloud config set project angular-yeti-258803
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials simple-cluster-02
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_ID" --password-stdin

deploy:
  provider: script
  script: bash ./deploy.sh


# before_install:
#   - docker build -t atambe/react-webapp02-client-test -f ./client/Dockerfile.dev ./client/

# script:
#   - docker run -e CI=true atambe/react-webapp02-client-test npm test

# after_success:
#   - docker build -t abhaytambe/react-webapp02-client ./client
#   - docker build -t abhaytambe/react-webapp02-nginx ./nginx
#   - docker build -t abhaytambe/react-webapp02-server ./server
#   - docker build -t abhaytambe/react-webapp02-worker ./worker
#    # connect with docker hub registry
#   - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_ID" --password-stdin
#   - docker push  abhaytambe/react-webapp02-client 
#   - docker push  abhaytambe/react-webapp02-nginx 
#   - docker push  abhaytambe/react-webapp02-server 
#   - docker push  abhaytambe/react-webapp02-worker 

  
