sudo: required
services:
  - docker

before_install:
  - docker build -t atambe/react-webapp02-client-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run -e CI=true atambe/react-webapp02-client-test npm test

after_success:
  - docker build -t abhaytambe/react-webapp02-client ./client
  - docker build -t atambe/react-webapp02-nginx ./nginx
  - docker build -t atambe/react-webapp02-server ./server
  - docker build -t atambe/react-webapp02-worker ./worker
   # connect with docker hub registry
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push  abhaytambe/react-webapp02-client 
  - docker push  atambe/react-webapp02-nginx 
  - docker push  atambe/react-webapp02-server 
  - docker push  atambe/react-webapp02-worker 

  
