apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      component: webapp-api
  template:
    metadata:
      labels:
        component: webapp-api
    spec:
      containers:
      - name: express-webapp02-api-server
        image: stephengrider/multi-server
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: webapp-redis-cluster-ip-service
          - name: REDIS_PORT
            value: '6379'
          - name: PGUSER
            value: postgres
          - name: PGHOST
            value: webapp-postgres-cluster-ip-service
          - name: PGPORT
            value: '5432'
          - name: PGDATABASE
            value: postgres
          - name: PGPASSWORD
            valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD