apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fib-worker
  template:
    spec:
      containers:
        - name: fib-worker-container
          image: stephengrider/multi-worker
          env:
            - name: REDIS_HOST
              value: webapp-redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'

    metadata:
      labels:
        component: fib-worker


